import vidPrev from "../img/catalog/photos/vid-prev.jpg";
import photo1 from "../img/catalog/photos/photo1.jpg";
import photo2 from "../img/catalog/photos/photo2.jpg";
import photo3 from "../img/catalog/photos/photo3.jpg";
import photo4 from "../img/catalog/photos/photo4.jpg";
import photo5 from "../img/catalog/photos/photo5.jpg";

export const solutions = [
    {
        id: 1,
        characteristics: {
            model: "Ecam201",
            resolution1: "2MP 1280*1080P",
            chipset: "Mstar313e+sc2235",
            resoluiton2: "1920*1080@25fps",
            lens: "2.8mm lens",
            ir: "12pcs/20M",
            material: "Metal",
            power: "DC1V/1A, PoE",
            waterproof: "IP66",
            warranty: "1 year",
            type: "Digital camera",
            tech: "Network IP",
        },
        description:
            "The camera has a metal housing that allows you to use for installation both outdoors and indoors. The camera has a built-in microphone. The camera can be connected to a video recorder for local archiving and to a cloud service.",
        translation: vidPrev,
        images: [
            [photo2, "L4EVTh~W00V?00jDOus;?vM{9Foc"],
            [photo3, "LCEe_R~WD$4o009Z%N?HxvRjIUs:"],
            [photo1, "LBAv?}xaIXxY00ofxtM}~WRjIVt7"],
            [photo4, "L2Ih810000_4.n^+0i9F00?w%NE0"],
            [photo5, "L3Frw@0200.7AyIV%Lxuv0_3pKRP"],
        ],
    },
    {
        id: 2,
        characteristics: {
            model: "Ecam201",
            resolution1: "2MP 1280*1080P",
            chipset: "Mstar313e+sc2235",
            resoluiton2: "1920*1080@25fps",
            lens: "2.8mm lens",
            ir: "12pcs/20M",
            material: "Metal",
            power: "DC1V/1A, PoE",
            waterproof: "IP66",
            warranty: "1 year",
            type: "Digital camera",
            tech: "Network IP",
        },
        description:
            "WiFi router with built-in modem. Support for any mobile operators. The ability to connect an external reinforced antenna, raises the quality and speed of the Internet. The ability to connect wired providers gives the presence of a WAN port. Thus 3g/4g modem gives a backup communication channel in case of disconnection of the main wired channel. Operating system openWRT allows you to configure the network for different network needs. Possibility to connect your video surveillance system and EasyCam cloud service",
        translation: vidPrev,
        images: [
            [photo2, "L4EVTh~W00V?00jDOus;?vM{9Foc"],
            [photo3, "LCEe_R~WD$4o009Z%N?HxvRjIUs:"],
            [photo1, "LBAv?}xaIXxY00ofxtM}~WRjIVt7"],
            [photo4, "L2Ih810000_4.n^+0i9F00?w%NE0"],
            [photo5, "L3Frw@0200.7AyIV%Lxuv0_3pKRP"],
        ],
    },
    {
        id: 3,
        characteristics: {
            model: "Ecam201",
            resolution1: "2MP 1280*1080P",
            chipset: "Mstar313e+sc2235",
            resoluiton2: "1920*1080@25fps",
            lens: "2.8mm lens",
            ir: "12pcs/20M",
            material: "Metal",
            power: "DC1V/1A, PoE",
            waterproof: "IP66",
            warranty: "1 year",
            type: "Digital camera",
            tech: "Network IP",
        },
        description:
            "The camera has a metal housing that allows you to use for installation both outdoors and indoors. The camera has a built-in microphone. The camera can be connected to a video recorder for local archiving and to a cloud service.",
        translation: vidPrev,
        images: [
            [photo2, "L4EVTh~W00V?00jDOus;?vM{9Foc"],
            [photo3, "LCEe_R~WD$4o009Z%N?HxvRjIUs:"],
            [photo1, "LBAv?}xaIXxY00ofxtM}~WRjIVt7"],
            [photo4, "L2Ih810000_4.n^+0i9F00?w%NE0"],
            [photo5, "L3Frw@0200.7AyIV%Lxuv0_3pKRP"],
        ],
    },
    {
        id: 4,
        characteristics: {
            model: "Ecam201",
            resolution1: "2MP 1280*1080P",
            chipset: "Mstar313e+sc2235",
            resoluiton2: "1920*1080@25fps",
            lens: "2.8mm lens",
            ir: "12pcs/20M",
            material: "Metal",
            power: "DC1V/1A, PoE",
            waterproof: "IP66",
            warranty: "1 year",
            type: "Digital camera",
            tech: "Network IP",
        },
        description:
            "WiFi router with built-in modem. Support for any mobile operators. The ability to connect an external reinforced antenna, raises the quality and speed of the Internet. The ability to connect wired providers gives the presence of a WAN port. Thus 3g/4g modem gives a backup communication channel in case of disconnection of the main wired channel. Operating system openWRT allows you to configure the network for different network needs. Possibility to connect your video surveillance system and EasyCam cloud service",
        translation: vidPrev,
        images: [
            [photo2, "L4EVTh~W00V?00jDOus;?vM{9Foc"],
            [photo3, "LCEe_R~WD$4o009Z%N?HxvRjIUs:"],
            [photo1, "LBAv?}xaIXxY00ofxtM}~WRjIVt7"],
            [photo4, "L2Ih810000_4.n^+0i9F00?w%NE0"],
            [photo5, "L3Frw@0200.7AyIV%Lxuv0_3pKRP"],
        ],
    },
    {
        id: 5,
        characteristics: {
            model: "Ecam201",
            resolution1: "2MP 1280*1080P",
            chipset: "Mstar313e+sc2235",
            resoluiton2: "1920*1080@25fps",
            lens: "2.8mm lens",
            ir: "12pcs/20M",
            material: "Metal",
            power: "DC1V/1A, PoE",
            waterproof: "IP66",
            warranty: "1 year",
            type: "Digital camera",
            tech: "Network IP",
        },
        description:
            "The camera has a metal housing that allows you to use for installation both outdoors and indoors. The camera has a built-in microphone. The camera can be connected to a video recorder for local archiving and to a cloud service.",
        translation: vidPrev,
        images: [
            [photo2, "L4EVTh~W00V?00jDOus;?vM{9Foc"],
            [photo3, "LCEe_R~WD$4o009Z%N?HxvRjIUs:"],
            [photo1, "LBAv?}xaIXxY00ofxtM}~WRjIVt7"],
            [photo4, "L2Ih810000_4.n^+0i9F00?w%NE0"],
            [photo5, "L3Frw@0200.7AyIV%Lxuv0_3pKRP"],
        ],
    },
    {
        id: 6,
        characteristics: {
            model: "Ecam201",
            resolution1: "2MP 1280*1080P",
            chipset: "Mstar313e+sc2235",
            resoluiton2: "1920*1080@25fps",
            lens: "2.8mm lens",
            ir: "12pcs/20M",
            material: "Metal",
            power: "DC1V/1A, PoE",
            waterproof: "IP66",
            warranty: "1 year",
            type: "Digital camera",
            tech: "Network IP",
        },
        description:
            "WiFi router with built-in modem. Support for any mobile operators. The ability to connect an external reinforced antenna, raises the quality and speed of the Internet. The ability to connect wired providers gives the presence of a WAN port. Thus 3g/4g modem gives a backup communication channel in case of disconnection of the main wired channel. Operating system openWRT allows you to configure the network for different network needs. Possibility to connect your video surveillance system and EasyCam cloud service",
        translation: vidPrev,
        images: [
            [photo2, "L4EVTh~W00V?00jDOus;?vM{9Foc"],
            [photo1, "LBAv?}xaIXxY00ofxtM}~WRjIVt7"],
            [photo3, "LCEe_R~WD$4o009Z%N?HxvRjIUs:"],
            [photo4, "L2Ih810000_4.n^+0i9F00?w%NE0"],
            [photo5, "L3Frw@0200.7AyIV%Lxuv0_3pKRP"],
        ],
    },
    {
        id: 7,
        characteristics: {
            model: "Ecam201",
            resolution1: "2MP 1280*1080P",
            chipset: "Mstar313e+sc2235",
            resoluiton2: "1920*1080@25fps",
            lens: "2.8mm lens",
            ir: "12pcs/20M",
            material: "Metal",
            power: "DC1V/1A, PoE",
            waterproof: "IP66",
            warranty: "1 year",
            type: "Digital camera",
            tech: "Network IP",
        },
        description:
            "The camera has a metal housing that allows you to use for installation both outdoors and indoors. The camera has a built-in microphone. The camera can be connected to a video recorder for local archiving and to a cloud service.",
        translation: vidPrev,
        images: [
            [photo2, "L4EVTh~W00V?00jDOus;?vM{9Foc"],
            [photo3, "LCEe_R~WD$4o009Z%N?HxvRjIUs:"],
            [photo1, "LBAv?}xaIXxY00ofxtM}~WRjIVt7"],
            [photo4, "L2Ih810000_4.n^+0i9F00?w%NE0"],
            [photo5, "L3Frw@0200.7AyIV%Lxuv0_3pKRP"],
        ],
    },
    {
        id: 8,
        characteristics: {
            model: "Ecam201",
            resolution1: "2MP 1280*1080P",
            chipset: "Mstar313e+sc2235",
            resoluiton2: "1920*1080@25fps",
            lens: "2.8mm lens",
            ir: "12pcs/20M",
            material: "Metal",
            power: "DC1V/1A, PoE",
            waterproof: "IP66",
            warranty: "1 year",
            type: "Digital camera",
            tech: "Network IP",
        },
        description:
            "WiFi router with built-in modem. Support for any mobile operators. The ability to connect an external reinforced antenna, raises the quality and speed of the Internet. The ability to connect wired providers gives the presence of a WAN port. Thus 3g/4g modem gives a backup communication channel in case of disconnection of the main wired channel. Operating system openWRT allows you to configure the network for different network needs. Possibility to connect your video surveillance system and EasyCam cloud service",
        translation: vidPrev,
        images: [
            [photo2, "L4EVTh~W00V?00jDOus;?vM{9Foc"],
            [photo3, "LCEe_R~WD$4o009Z%N?HxvRjIUs:"],
            [photo1, "LBAv?}xaIXxY00ofxtM}~WRjIVt7"],
            [photo4, "L2Ih810000_4.n^+0i9F00?w%NE0"],
            [photo5, "L3Frw@0200.7AyIV%Lxuv0_3pKRP"],
        ],
    },
];
